apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64 
      
      containers:
      - name: backend
        image: caam-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongo-uri-secret
                key: MONGODB_URI
          - name: EMAIL_ID
            valueFrom:
              secretKeyRef:
                name: email-secret
                key: EMAIL_ID
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: email-secret
                key:  EMAIL_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: email-secret
                key:  SECRET_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
