apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:4.4
        command:
        - "sh"
        - "-c"
        - |
          # Wait for MongoDB to be ready
          until mongo --host mongo-0.mongodb.default.svc.cluster.local --eval "db.adminCommand('ping')"; do
            echo "Waiting for MongoDB..."
            sleep 5
          done
          
          # Initialize replica set
          mongo --host mongodb-0.mongodb.default.svc.cluster.local <<EOF
          rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017" },
              { _id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017" },
              { _id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017" }
            ]
          })
          EOF
      restartPolicy: OnFailure
